# Rapport - Python par la pratique - Samuel Meystre
## Introduction
Lors du 2ème semestre de 3ème année, le cours à choix de python par la pratique
a été choisi pour pouvoir approfondir dans ce langage de programmation.

Car nous avons utilisé ce langage dans le cadre du cours TSA, mais sans 
aller dans les détails (utilisation uniquement de numpy, matplotlib, scipy ou
un autre module python pour le traitement du signal).

Le cours Python par la pratique permet de combler ce que nous avions pas vu lors du cours TSA.
Notamment avec les règles de programmation (zen de Python), les sructures de données, Pandas, 
Click ou encore l'utilisation de templates HTML avec Jinja2 et Flask.

## Structures de données
### Scalaires
Nous avons vu l'utilisation des scalaires dans python et également vu comment s'en servir.

In [532]:
i = 9           # integer
f = 5.674       # float
c = 2 + 3j      # complex
s = 'Coucou'    # string
b = True        # boolean
n = None

Le type string ne peut pas être modifié comme montré ci-dessous:

In [533]:
# s[1] = 'i'

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[40], line 1
----> 1 s[1] = 'i'

TypeError: 'str' object does not support item assignment

### Conteneurs
En plus des scalaires, nous avons vu également les différents conteneurs présents en Python:

#### Listes []
Les listes peuvent s'apparenter à des tableaux en C.
Elles ne sont pas hashable et elles possèdent un itérateur.

In [534]:
l = []      # Création d'une liste vide
l = ['Chien', 'Chat', 'Souris', 'Chat', 'Chat', 'Hamster']
print(l)

['Chien', 'Chat', 'Souris', 'Chat', 'Chat', 'Hamster']


In [535]:
l[-1]

'Hamster'

In [536]:
l[2:-2]

['Souris', 'Chat']

In [537]:
l[::2]

['Chien', 'Souris', 'Chat']

In [538]:
# ajout d'un élément dans une liste
l.append('Cochon')
print(l)

['Chien', 'Chat', 'Souris', 'Chat', 'Chat', 'Hamster', 'Cochon']


In [539]:
# comptage des éléments
l.count('Chat')

3

In [540]:
# itérateur
iterator = iter(l)

print(next(iterator)) 
print(next(iterator)) 
print(next(iterator)) 

Chien
Chat
Souris


In [541]:
# hash d'une liste (ERROR)
# print(hash(l))

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[29], line 2
      1 # hash d'une liste (ERROR)
----> 2 print(hash(l))

TypeError: unhashable type: 'list'

#### Tuples ()
Le tuple est un conteneur ressemblant à une liste, mais qui est hashable. Le tuple ne peut pas être modifié
et il est itérable.

In [542]:
t = (1,2,3,4)
t

(1, 2, 3, 4)

In [543]:
# hash d'un tuple
print(hash(t))

590899387183067792


In [544]:
# itérateur
iterator = iter(t)

print(next(iterator)) 
print(next(iterator)) 
print(next(iterator)) 

1
2
3


In [545]:
# Modification d'un tuple (ERROR)
# t[2] = 0

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[55], line 2
      1 # Modification d'un tuple (ERROR)
----> 2 t[2] = 0

TypeError: 'tuple' object does not support item assignment

#### Dictionnaires {}

Le dictionnaire est conteneur ayant une clé et une valeur associée à la clé.
Les clées sont hashable.

In [546]:
d = {23: 'vingt-trois', 42: 'La réponse', 95: 'neuf-cinq'}
d

{23: 'vingt-trois', 42: 'La réponse', 95: 'neuf-cinq'}

In [547]:
d.items()

dict_items([(23, 'vingt-trois'), (42, 'La réponse'), (95, 'neuf-cinq')])

In [548]:
d.values()

dict_values(['vingt-trois', 'La réponse', 'neuf-cinq'])

In [549]:
d.keys()

dict_keys([23, 42, 95])

In [550]:
d[42]

'La réponse'

#### Set {}

Le set est un dictionnaire avec que des clés.

In [551]:
st = {23, 42, 95}
st

{23, 42, 95}

## Fonctions

Le langage Python permet de créer ses fonctions.

In [552]:
def my_func(a, b):
    return a**b

In [553]:
c = my_func(4, 2)
c

16

## Classes

Le langage Python est orienté objet. Il permet donc de créer des classes.

In [554]:
from unidecode import unidecode

In [555]:
class my_class:
    def __init__(self, words):
        self.words = words
        self.counter = len(words)
    
    def __iter__(self):
        return self
    
    def __next__(self):
        if self.counter <= 0:
            raise ValueError('Plus de mots')
        self.counter -= 1
        word = self.words[self.counter]
        word = unidecode(word)
        word = word.upper()
        return word

#### Ouvrir des fichiers

In [556]:
filename = 'mots.txt'

fp = open(filename, 'r') # 'w', 'a'
fp.read() # Lis tout le fichier
fp.readline() # Lis la prochaine ligne
fp.readlines() # Lis toutes les lignes 
fp.close()

Ou:

In [557]:
words_table = []
with open(filename,'r') as fd:
    while line := fd.readline():
        word = line.split('\n')[0]
        words_table.append(word)

#### Instanciation d'une classe

In [558]:
mots = my_class(words_table)

for k in range(len(words_table)):
    print(next(mots))

CHENE
FURIEUX
LOOPING
RUISSEAU
BRUTE
TRUITE


## Tests, destructuration, zip, déréférencement et surcharge

### Tests

#### in

Ce test permet de vérifier si une valeur souhaitée se trouve dans un conteneur

In [559]:
l = [1,2,3,4,5,6]
5 in l

True

In [560]:
0 in l

False

#### all

Retourne `True` si tous les éléments sont vrai

In [561]:
la = ['True', True, 1, 'Oiseau']
all(la)

True

In [562]:
lna = [78, 'Truite', True, 'Fraise', False]
all(lna)

False

#### any

Retourn `True` si au moins un élément est vrai

In [563]:
any(lna)

True

In [564]:
lnaa = [0,0,0,0,0,0,None,False]
any(lnaa)

False

### Destructuration

La destructuration en Python permet, par exemple, d'échanger deux valeurs ou de récupérer
la valeur de chaque élément d'une liste, d'un tuple ou d'un dictionnaire.

In [565]:
a = 9
b = 5
a, b

(9, 5)

In [566]:
a, b = b, a
a, b    # les valeurs ont été échangée

(5, 9)

In [567]:
l = [1,2,3,4]
a,b,c,d = l
a,b,c,d

(1, 2, 3, 4)

In [568]:
d = {51: 'Apéro', 42: 'Réponse'}
a, b = d
a, b

(51, 42)

Faire `a, b = d` ne prend que les clés du dictionnaire. Pour avoir les valeurs, voici ce qu'il faut faire:

In [569]:
a, b = d.values()
a, b

('Apéro', 'Réponse')

La déstructuration d'une liste fonctionne aussi avec l'opérateur `*`. \
Suivant sa position, cela permet de récupérer, par exemple, la première valeur de la liste puis tout le reste dans une nouvelle variable/liste.

In [570]:
head, *reste = l
print(head)
print(reste)

1
[2, 3, 4]


In [571]:
*head, reste = l
print(head)
print(reste)

[1, 2, 3]
4


En plus de tout cela, la desctructuration permet également d'extraire l'indice d'une valeur dans une boucle `for`.

In [572]:
for i, v in enumerate(l):
    print(f'Indices: {i}, Valeurs: {v}')

Indices: 0, Valeurs: 1
Indices: 1, Valeurs: 2
Indices: 2, Valeurs: 3
Indices: 3, Valeurs: 4


### Zip
Cet opérateur permet de "fusionner" deux listes ensemble.

In [573]:
firstnames = ['John', 'Emmet', 'Luke']
lastnames = ['Doe', 'Brown', 'Skywalker']

list(zip(firstnames, lastnames))

[('John', 'Doe'), ('Emmet', 'Brown'), ('Luke', 'Skywalker')]

Pour que ce soit plus joli à l'affichage:

In [574]:
[' '.join(x) for x in list(zip(firstnames, lastnames))]

['John Doe', 'Emmet Brown', 'Luke Skywalker']

### Déréférencement
Le déréférencement se fait à l'aide de `*args` ou `**kwargs` dans une fonction. \
Cela permet de récupéréer tous les arguments entrés dans la fonction

In [575]:
def foo(*args, **kwargs):
    print(args)
    print(kwargs)

In [576]:
foo(8,2,3,'pamplemousse',42)

(8, 2, 3, 'pamplemousse', 42)
{}


Une fonction utilisant le `**kwargs`:

In [577]:
def operate(a, b, **kwargs):
    if 'add' in kwargs:
        print(f'{a}+{b} = {a+b}')
    if 'sub' in kwargs:
        print(f'{a}-{b} = {a-b}')

In [578]:
operate(5, 4, add=True)
operate(5, 4, sub=True)

5+4 = 9
5-4 = 1


### Surcharge
La surcharge d'un opérateur permet de se passer, dans le cadre d'une classe, de l'appel de la fonction addition, par exemple.

In [579]:
class Number:
    def __init__(self, number):
        self.number = number
    def __add__(self, number):
        self.number += number

In [580]:
n = Number(42)
n.number

42

In [581]:
n + 9
n.number

51

## Compréhension, lambda, map et filter
### Compréhension
La compréhension permet de travailler avec une liste sans devoir passer par une boucle `for` et donc, d'optimiser le code.

In [582]:
l = ['Chat','Souris','Chien','Souris','Chat']
l

['Chat', 'Souris', 'Chien', 'Souris', 'Chat']

Admettons qu'il faut changer "Chat" par "Tom". En compréhension cela donne:

In [583]:
nl = ['Tom' if x=='Chat' else x for x in l]
nl

['Tom', 'Souris', 'Chien', 'Souris', 'Tom']

### Lambda
`lambda` est une fonction Python contenant qu'une seule expression. Elle permet de faire des fonctions simple si 
la compréhension deviet trop complexe.

In [584]:
x = lambda a, b : a**b
res = x(2, 3)
res

8

### Map
`map` est une fonction qui retourne un itérable du résultat.

In [585]:
def double_num(n):
    return n + n

t = (1, 2, 3, 4)

res = map(double_num, t)
print(list(res))

[2, 4, 6, 8]


La fonction `map`peut être utilisée avec `lambda` pour afficher, par exemple, directement le résultat sans passer par une fonction.

In [586]:
t = (5, 6, 7, 8)
res = map(lambda x: x + x, t)
print(list(res))

[10, 12, 14, 16]


### Filter
La fonction `filter` permet de filtrer des éléments d'un conteneur selon une condition donnée. \
Comme pour `map`, `filter` peut être directement utilisé avec `lambda`, ce qui est le cas usuellement dans la programmation en Python

In [587]:
mots = ['souris', 'chat', 'chien', 'singe', 'oiseau', 'ornythorynque']
thr = 6
mots_tri = list(filter(lambda x: len(x) >= thr, mots))
mots_tri

['souris', 'oiseau', 'ornythorynque']

## Namedtuple
Le module `namedtuple` contribue à de faire des `tuple` qui permettent d'accéder aux valeurs avec
noms descriptif et le `t.`au lieu des indices.

In [588]:
from collections import namedtuple

Cat = namedtuple('Cat',('name','genre'))
c = Cat('Felix','MALE')
c

Cat(name='Felix', genre='MALE')

In [589]:
c.name

'Felix'

In [590]:
c.genre

'MALE'

In [591]:
#c.name = 'oops'

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[334], line 1
----> 1 c.name = 'oops'

AttributeError: can't set attribute

## Numpy
Numpy est un module Python ayant comme particularité de faire des calculs matriciels (à l'image de MatLab). \
Car, en Python, il n'est pas possible de faire des opérations mathématiques avec deux listes, cela donnera un résultat
totalement différent à ce qui est attendu. \
Exemple:

In [592]:
l1 = [1,2,3]
l2 = [4,5,6]

l3 = l1+l2
l3

[1, 2, 3, 4, 5, 6]

Faire une addition entre deux listes équivaut à les concaténeer.\
Pour faire une addition entre deux listes (vecteurs) il faut utiliser le module Numpy.

In [593]:
import numpy as np

v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

v3 = v1+v2
v3

array([5, 7, 9])

Avec Numpy, c'est le monde de MatLab qui s'ouvre sur Python. Il est possible d'avoir toutes les fonctions mathématiques.\
Les matrices ou vecteurs créés avec Numpy sont également compatibles avec la notation des indices de Python.

In [594]:
v4 = v1*v2
v4

array([ 4, 10, 18])

In [595]:
v = np.arange(1,11)
v

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [596]:
v[1]

2

In [597]:
v[-1]

10

In [599]:
v[3:6]

array([4, 5, 6])

In [600]:
s = np.sin(v)
s

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [601]:
pi = np.pi
pi

3.141592653589793

## Click
Click est un module Python assurant l'entrée d'arguments avec le clavier de l'ordinateur.